'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { Printer, X, Activity, User, FileText } from 'lucide-react';

function NonFinancialStatusReportContent() {
  const searchParams = useSearchParams();
  const fromDate = searchParams.get('fromDate') || '';
  const toDate = searchParams.get('toDate') || '';

  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [userName, setUserName] = useState('IMAGEE OWNER');

  const [ordersCount, setOrdersCount] = useState(0);
  const [completedCount, setCompletedCount] = useState(0);
  const [pendingCount, setPendingCount] = useState(0);

  useEffect(() => {
    const userRaw = localStorage.getItem('medfile-user');
    if (userRaw) {
      try {
        const user = JSON.parse(userRaw);
        if (user.name) setUserName(user.name);
      } catch(e) {}
    }
  }, []);

  useEffect(() => {
    fetch('/api/bills/in-process')
      .then(res => res.json())
      .then(bills => {
        if (Array.isArray(bills)) {
          // Parse dates for filtering
          const parseDateStr = (dStr: string) => {
            if (!dStr) return null;
            const parts = dStr.split('-');
            if (parts.length !== 3) return null;
            const months: Record<string, number> = { 'Jan':0, 'Feb':1, 'Mar':2, 'Apr':3, 'May':4, 'Jun':5, 'Jul':6, 'Aug':7, 'Sep':8, 'Oct':9, 'Nov':10, 'Dec':11 };
            return new Date(parseInt(parts[2]), months[parts[1]], parseInt(parts[0]));
          };

          const fDate = parseDateStr(fromDate);
          const tDate = parseDateStr(toDate);

          let filtered = bills;
          if (fDate && tDate) {
            // Set tDate to end of day
            tDate.setHours(23, 59, 59, 999);
            filtered = filtered.filter(b => {
              const bd = new Date(b.billDate);
              return bd >= fDate && bd <= tDate;
            });
          }
          
          setData(filtered);
          
          let tOrders = 0;
          let tCompleted = 0;
          let tPending = 0;
          
          filtered.forEach((b: any) => {
            b.orders.forEach((o: any) => {
              tOrders++;
              if (o.resultStatus === 'Completed' || o.resultStatus === 'Verified') {
                tCompleted++;
              } else {
                tPending++;
              }
            });
          });
          
          setOrdersCount(tOrders);
          setCompletedCount(tCompleted);
          setPendingCount(tPending);
        }
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  }, [fromDate, toDate]);

  const handlePrint = () => {
    window.print();
  };

  const handleExit = () => {
    window.close();
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', background: '#f8fafc', color: '#64748b' }}>
        <div className="loader"></div>
        <style>{`.loader { width: 40px; height: 40px; border: 4px solid #e2e8f0; border-top-color: #3b82f6; border-radius: 50%; animation: spin 1s linear infinite; } @keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  return (
    <div className="modern-report-wrapper">
      <div className="modern-report-container">
        
        {/* Header Section */}
        <div className="report-header no-print">
          <div className="report-brand">
            <div className="brand-icon"><Activity size={20} /></div>
            <div>
              <h1 className="brand-title">Non-Financial Status Report</h1>
              <p className="brand-subtitle">
                {data.length > 0 && fromDate && toDate ? `Between the dates ${fromDate} and ${toDate}` : 'Order Status Tracking & Breakdown'}
              </p>
            </div>
          </div>

          <div className="report-actions">
            <button onClick={handleExit} className="modern-btn btn-secondary">
              <X size={16} /> <span>Close</span>
            </button>
            <button onClick={handlePrint} className="modern-btn btn-primary">
              <Printer size={16} /> <span>Print Report</span>
            </button>
          </div>
        </div>

        {/* User Badge */}
        <div className="user-badge-section no-print">
          <div className="user-badge">
            <User size={14} className="user-icon" />
            <span>Generated by <strong>{userName}</strong></span>
          </div>
        </div>

        {/* Print Only Header */}
        <div className="print-only-header print-only" style={{ textAlign: 'center', marginBottom: 24, borderBottom: 'none' }}>
          <h2 style={{ fontSize: 18, marginBottom: 6 }}>Non Financial Status Report{fromDate && toDate ? ` Between the dates ${fromDate} and ${toDate}` : ''}</h2>
          <p>User: {userName} • Printed: {new Date().toLocaleDateString()}</p>
        </div>

        {/* Table Container */}
        <div className="table-card">
          
          {data.length > 0 && (
            <div className="report-summary">
              <div className="summary-item">
                <span className="summary-label">Orders Count</span>
                <span className="summary-separator">:</span>
                <span className="summary-value">{ordersCount}</span>
              </div>
              <div className="summary-item">
                <span className="summary-label">Dispatched Count</span>
                <span className="summary-separator">:</span>
                <span className="summary-value">0</span>
              </div>
              <div className="summary-item">
                <span className="summary-label">Completed Count</span>
                <span className="summary-separator">:</span>
                <span className="summary-value">{completedCount}</span>
              </div>
              <div className="summary-item">
                <span className="summary-label">Pending Count</span>
                <span className="summary-separator">:</span>
                <span className="summary-value">{pendingCount}</span>
              </div>
            </div>
          )}

          <div className="table-responsive">
            <table className="modern-table">
              <thead>
                <tr>
                  <th style={{ width: '10%' }}>Date</th>
                  <th style={{ width: '10%' }}>Bill No</th>
                  <th style={{ width: '18%' }}>Patient Name</th>
                  <th style={{ width: '6%', textAlign: 'center' }}>Age</th>
                  <th style={{ width: '8%' }}>Gender</th>
                  <th style={{ width: '20%' }}>Order</th>
                  <th style={{ width: '13%' }}>Status</th>
                  <th style={{ width: '15%' }}>Referred By</th>
                </tr>
              </thead>
              <tbody>
                {data.flatMap((bill: any) => {
                  const date = new Date(bill.billDate);
                  const formattedDate = `${date.getDate().toString().padStart(2, '0')}/${(date.getMonth() + 1).toString().padStart(2, '0')}/${date.getFullYear().toString().slice(-2)}`;
                  
                  return bill.orders.map((o: any, idx: number) => {
                    const isMale = bill.patient.gender === 'M';
                    const isFemale = bill.patient.gender === 'F';
                    const genderClass = isMale ? 'badge-male' : isFemale ? 'badge-female' : 'badge-neutral';
                    const genderText = isMale ? 'Male' : isFemale ? 'Female' : bill.patient.gender;

                    const isCompleted = o.resultStatus === 'Completed' || o.resultStatus === 'Verified';
                    const statusClass = isCompleted ? 'badge-status-completed' : 'badge-status-pending';

                    return (
                      <tr key={o.id} className="table-row">
                        <td className="cell-date">{idx === 0 ? formattedDate : ''}</td>
                        <td className="cell-id">{idx === 0 ? `#${bill.billNumber}` : ''}</td>
                        <td className="cell-name">{idx === 0 ? bill.patient.name : ''}</td>
                        <td align="center" className="cell-age">{idx === 0 ? (bill.patient.age ? `${bill.patient.age}y` : '-') : ''}</td>
                        <td>{idx === 0 ? <span className={`gender-badge ${genderClass}`}>{genderText}</span> : ''}</td>
                        <td className="cell-orders">{o.orderName}</td>
                        <td><span className={`status-badge ${statusClass}`}>{o.resultStatus}</span></td>
                        <td className="cell-source">{idx === 0 ? (bill.patient.source || 'DR SELF') : ''}</td>
                      </tr>
                    );
                  });
                })}
                {data.length === 0 && (
                  <tr>
                    <td colSpan={8} className="empty-state">
                      <div className="empty-content">
                        <FileText size={32} />
                        <p>No active bills currently in process.</p>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

        * {
          box-sizing: border-box;
        }

        .modern-report-wrapper {
          min-height: 100vh;
          background: #f1f5f9;
          font-family: 'Inter', sans-serif;
          padding: 40px 20px;
          color: #334155;
        }

        .modern-report-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        /* Header */
        .report-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 24px;
          background: #ffffff;
          padding: 20px 24px;
          border-radius: 16px;
          box-shadow: 0 4px 20px rgba(0, 0, 0, 0.03);
        }

        .report-brand {
          display: flex;
          align-items: center;
          gap: 16px;
        }

        .brand-icon {
          background: linear-gradient(135deg, #10b981, #059669);
          color: white;
          width: 48px;
          height: 48px;
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 4px 12px rgba(16, 185, 129, 0.3);
        }

        .brand-title {
          margin: 0;
          font-size: 20px;
          font-weight: 700;
          color: #0f172a;
          letter-spacing: -0.5px;
        }

        .brand-subtitle {
          margin: 4px 0 0;
          font-size: 13px;
          color: #64748b;
          font-weight: 500;
        }

        /* Buttons */
        .report-actions {
          display: flex;
          gap: 12px;
        }

        .modern-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 20px;
          border-radius: 10px;
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s ease;
          border: none;
        }

        .btn-secondary {
          background: #f1f5f9;
          color: #475569;
        }

        .btn-secondary:hover {
          background: #e2e8f0;
          color: #0f172a;
        }

        .btn-primary {
          background: linear-gradient(135deg, #f97316, #ea580c);
          color: white;
          box-shadow: 0 4px 12px rgba(234, 88, 12, 0.3);
        }

        .btn-primary:hover {
          transform: translateY(-1px);
          box-shadow: 0 6px 16px rgba(234, 88, 12, 0.4);
        }

        /* User Badge */
        .user-badge-section {
          display: flex;
          justify-content: flex-end;
          margin-bottom: 24px;
        }

        .user-badge {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          background: #e0f2fe;
          color: #0369a1;
          padding: 8px 16px;
          border-radius: 20px;
          font-size: 13px;
          font-weight: 500;
          border: 1px solid #bae6fd;
        }

        .user-icon {
          opacity: 0.8;
        }

        /* Table Card */
        .table-card {
          background: #ffffff;
          border-radius: 16px;
          box-shadow: 0 10px 30px rgba(0, 0, 0, 0.04);
          overflow: hidden;
          border: 1px solid #f1f5f9;
        }

        .table-responsive {
          width: 100%;
          overflow-x: auto;
        }

        .modern-table {
          width: 100%;
          border-collapse: collapse;
          text-align: left;
        }

        .modern-table th {
          background: #f8fafc;
          padding: 16px 20px;
          font-size: 12px;
          font-weight: 600;
          color: #64748b;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          border-bottom: 2px solid #e2e8f0;
        }

        .modern-table td {
          padding: 16px 20px;
          font-size: 14px;
          border-bottom: 1px solid #f1f5f9;
          vertical-align: middle;
        }

        .table-row {
          transition: background 0.15s ease;
        }

        .table-row:hover {
          background: #f8fafc;
        }

        /* Cells */
        .cell-date {
          color: #64748b;
          font-size: 13px;
          font-weight: 500;
        }

        .cell-id {
          font-family: monospace;
          color: #0f172a;
          font-weight: 600;
        }

        .cell-name {
          color: #0f172a;
          font-weight: 600;
          text-transform: capitalize;
        }

        .cell-age {
          color: #475569;
          font-weight: 500;
        }

        .cell-orders {
          color: #475569;
          line-height: 1.5;
        }

        .cell-source {
          color: #64748b;
          font-size: 13px;
          text-transform: capitalize;
        }

        /* Badges */
        .gender-badge {
          display: inline-block;
          padding: 4px 10px;
          border-radius: 6px;
          font-size: 12px;
          font-weight: 600;
        }

        .badge-male {
          background: #eff6ff;
          color: #2563eb;
        }

        .badge-female {
          background: #fdf2f8;
          color: #db2777;
        }

        .badge-neutral {
          background: #f1f5f9;
          color: #475569;
        }
        
        .status-badge {
          display: inline-block;
          padding: 4px 10px;
          border-radius: 6px;
          font-size: 11px;
          font-weight: 600;
          text-transform: uppercase;
        }

        .badge-status-completed {
          background: #dcfce7;
          color: #166534;
        }

        .badge-status-pending {
          background: #fee2e2;
          color: #991b1b;
        }

        .report-summary {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 16px 60px;
          padding: 20px 24px;
          background: #f8fafc;
          border-bottom: 2px solid #e2e8f0;
          font-size: 14px;
        }

        .summary-item {
          display: flex;
          align-items: center;
          justify-content: flex-start;
          gap: 16px;
        }

        .summary-label {
          font-weight: 600;
          color: #334155;
          width: 140px;
        }

        .summary-separator {
          color: #94a3b8;
          font-weight: bold;
        }

        .summary-value {
          font-weight: 700;
          color: #0f172a;
          font-size: 15px;
        }

        /* Empty State */
        .empty-state {
          padding: 60px 20px !important;
        }

        .empty-content {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          color: #94a3b8;
          gap: 12px;
        }

        .empty-content p {
          margin: 0;
          font-size: 15px;
          font-weight: 500;
        }

        .print-only {
          display: none;
        }

        /* Print Styles */
        @media print {
          @page { margin: 15mm; }
          
          .no-print { display: none !important; }
          .print-only { display: block !important; }

          .modern-report-wrapper {
            background: transparent !important;
            padding: 0 !important;
            color: #0f172a !important;
          }

          .print-only-header {
            margin-bottom: 24px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 12px;
          }

          .print-only-header h2 {
            margin: 0 0 4px 0;
            font-size: 20px;
            color: #0f172a;
            text-align: center;
          }

          .print-only-header p {
            margin: 0;
            font-size: 13px;
            color: #64748b;
            text-align: center;
          }

          .table-card {
            box-shadow: none !important;
            border: none !important;
            border-radius: 0 !important;
          }

          .modern-table {
            border: 1px solid #e2e8f0;
          }

          .modern-table th, .modern-table td {
            border: 1px solid #e2e8f0 !important;
            padding: 12px 16px;
            color: #334155 !important;
          }

          .modern-table th {
            background: #f8fafc !important;
            -webkit-print-color-adjust: exact;
            border-bottom: 2px solid #cbd5e1 !important;
            color: #475569 !important;
          }

          .gender-badge, .status-badge {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }

          .report-summary {
            background: #f8fafc !important;
            -webkit-print-color-adjust: exact;
            border: 1px solid #e2e8f0;
            border-bottom: none;
            padding: 16px 20px;
            gap: 8px 60px;
          }
        }
      `}</style>
    </div>
  );
}

export default function NonFinancialStatusReport() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <NonFinancialStatusReportContent />
    </Suspense>
  );
}
