import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const sourcesData = [
  { name: 'IMID001', status: 'Active' },
  { name: 'IMID002', status: 'Active' },
  { name: 'IMID003', status: 'Active' },
  { name: 'IMID004', status: 'Active' },
  { name: 'IMID005', status: 'Active' },
  { name: 'IMID006', status: 'Active' },
  { name: 'ramana mrkt', status: 'InActive' },
  { name: 'Sai', status: 'Active' },
  { name: 'C/O SRINIVAS MRK .', status: 'InActive' },
  { name: 'C/O SRINIVAS MRK', status: 'InActive' },
  { name: 'rajesh mrkt', status: 'Active' },
  { name: '````````', status: 'Active' },
  { name: 'L', status: 'Active' },
  { name: 'C/O ARUNA', status: 'Active' },
  { name: 'VANASTALI HELTHA CARE', status: 'Active' },
  { name: 'PARAMITHA RAJU', status: 'Active' },
  { name: 'SURESH', status: 'Active' },
  { name: 'KISHORE', status: 'Active' },
  { name: 'TANVI HOSPITAL', status: 'Active' },
  { name: 'DR VIKAS', status: 'Active' },
  { name: 'DR YASHWASHWANTH', status: 'Active' },
  { name: 'DR SRIKANTH KOLLUJU', status: 'Active' },
  { name: 'C/O ORANGE HOSPITAL', status: 'Active' },
  { name: 'C/O RAMESH', status: 'Active' },
  { name: 'C/O SRINIVAS', status: 'Active' },
  { name: 'DR NARESH', status: 'Active' },
  { name: 'DR RAMU', status: 'Active' },
  { name: 'J S HOSPITAL', status: 'Active' },
  { name: 'PRASIDH HOSPITAL', status: 'Active' },
  { name: 'SRI KRISHNA HOSPITAL', status: 'Active' },
  { name: 'PRABHAKAR', status: 'Active' },
  { name: 'SRI MULTISPECIALITY HOSPITAL', status: 'Active' },
  { name: 'C/O KISHORE', status: 'Active' },
  { name: 'OLIVE', status: 'Active' },
  { name: 'OLIVE CLINIC', status: 'Active' },
  { name: 'OLCLINIC', status: 'Active' },
  { name: 'OLIVE SUPER SPECIALITY HOSPITAL', status: 'Active' },
  { name: 'C/O SUNRICE HOSPITAL', status: 'Active' },
  { name: 'C/O RAJU', status: 'Active' },
  { name: 'VAMSHI', status: 'Active' },
  { name: 'AYYAN DIAG', status: 'Active' },
  { name: 'C/O ABHAYA HOSPITAL', status: 'Active' },
  { name: 'C/O CHETHANA HOSPITAL', status: 'Active' },
  { name: 'DBR DIAG', status: 'Active' },
  { name: 'MAXI', status: 'Active' },
  { name: 'SUNRISE', status: 'Active' },
  { name: 'DR MANJUNATH', status: 'Active' },
  { name: 'VANASTHALI HOSPITAL', status: 'Active' },
  { name: 'DR SUJATHA', status: 'Active' },
  { name: 'C/O GOPI', status: 'Active' },
  { name: 'SHEKAR POCHAMPALLY', status: 'Active' },
  { name: 'DBR RAMANA', status: 'Active' },
  { name: 'C/O KALYAN', status: 'Active' },
  { name: 'MAXICURE HOSPITAL', status: 'Active' },
  { name: 'C/O VENKANNA LITTLE STAR', status: 'Active' },
  { name: 'GK HOSPITAL', status: 'Active' },
  { name: 'C/O SUNRISE HOSPITAL', status: 'Active' },
  { name: 'SHADOW HOSPITAL', status: 'Active' },
  { name: 'SHADOW HOSPITAL METTU', status: 'Active' },
  { name: 'DR.SHWETHA S', status: 'Active' },
  { name: 'AYAAN DIAG', status: 'Active' },
  { name: 'C/O MANOGNA', status: 'Active' },
  { name: 'AADHYA', status: 'Active' },
  { name: 'DR KOTHAKURMA LAKSHMAN', status: 'Active' },
  { name: 'METRO DIAGNOSTICS', status: 'Active' },
  { name: 'DR RATNA KISHORE DAVID', status: 'Active' },
  { name: 'MALLIKARJUNA LAB', status: 'Active' },
  { name: 'VISWAS HOSPITAL', status: 'Active' },
  { name: 'C/O MAXI CURE', status: 'Active' },
  { name: 'C/O GK NARESH', status: 'Active' },
  { name: 'C/O DR VIKAS', status: 'Active' },
  { name: 'C/O PRASIDH HOSP', status: 'Active' },
  { name: 'C/O GVK HOSP', status: 'Active' },
  { name: 'C/O SHADOW HOSP', status: 'Active' },
  { name: 'MAHESH', status: 'Active' },
  { name: 'SRI SOMYA HOSPITAL', status: 'Active' },
  { name: 'DR PRAVEEN KUMAR SIR', status: 'Active' },
  { name: 'SRIVEN HOSPITAL', status: 'Active' },
  { name: 'C/O PRAVEEN KUMARE', status: 'Active' },
  { name: 'C/O DR PRAVEEN KUMARE', status: 'Active' },
  { name: 'DR Y KALYAN', status: 'Active' },
  { name: 'C/O RAMNA', status: 'Active' },
  { name: 'C/O NARESH', status: 'Active' },
  { name: 'DR DILIP REDDY', status: 'Active' },
  { name: 'DR BHANU', status: 'Active' },
  { name: 'DR JHANGEER', status: 'Active' },
  { name: 'GANESH', status: 'Active' },
  { name: 'AMULYA', status: 'Active' },
  { name: 'C/O DR MANJUNATH', status: 'Active' },
  { name: 'PULSE HOSPITAL', status: 'Active' },
  { name: 'C/O ARCANA', status: 'Active' },
  { name: 'C/O ORANGE HOSPITAL.', status: 'Active' },
  { name: 'DR ASHOK VARDHAN', status: 'Active' },
  { name: 'C/O LITTLE STAR', status: 'Active' },
  { name: 'C/O VAMSI', status: 'Active' },
  { name: 'C/O AADHYA HOSPITAL', status: 'Active' },
  { name: 'DR ANITHA VINOD', status: 'Active' },
  { name: 'DR SHASHEENDRA', status: 'Active' },
  { name: 'C/O SHREYS HOSPITAL', status: 'Active' },
  { name: 'SRINIVAS', status: 'Active' },
  { name: 'DR MD ASLAM', status: 'Active' },
  { name: 'C/O RAJASHKARE', status: 'Active' },
  { name: 'C/O RAAMU', status: 'Active' },
  { name: 'DR A S NAIDU', status: 'Active' },
  { name: 'N SABITHA', status: 'Active' },
  { name: 'TESLA DIAGNOSTICS', status: 'Active' },
  { name: 'RAJU PARAMITHA', status: 'Active' },
  { name: 'SELF', status: 'Active' },
  { name: 'C/O SRINIVAS GK NA', status: 'Active' },
  { name: 'C/O MAXI CURE USHA', status: 'Active' },
  { name: 'C/O TAJ UDDIN', status: 'Active' },
  { name: 'C/O ANURADHA ORANGE HOS', status: 'Active' },
  { name: 'C/O VIVEERA HOSP', status: 'Active' },
  { name: 'LATHIKA POLY CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS MANJUNATH RAMESH', status: 'Active' },
  { name: 'C/O SRI BAVITHA DIAG', status: 'Active' },
  { name: 'C/O SRI BHAVAYA DIG', status: 'Active' },
  { name: 'C/O SRINIVAS TEJA', status: 'Active' },
  { name: 'C/O SRINIVAS SATHISH', status: 'Active' },
  { name: 'C/O SRINIVAS KALYAN', status: 'Active' },
  { name: 'C/O SRINIVAS DBR', status: 'Active' },
  { name: 'C/O SRINIVAS VENKATESH VANASTHALI HOSP', status: 'Active' },
  { name: 'C/O DR JHANSI LAKSHMI BAI', status: 'Active' },
  { name: 'C/O SRINIVAS VENU KUMARI', status: 'Active' },
  { name: 'C/O DR B NARESH KUMA', status: 'Active' },
  { name: 'C/O MUKTA CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS VAMSHI', status: 'Active' },
  { name: 'C/O BIRTH RIGHT', status: 'Active' },
  { name: 'C\\O GOPI', status: 'Active' },
  { name: 'C/O RAGHU', status: 'Active' },
  { name: 'VEMA REDY KAVITHA', status: 'Active' },
  { name: 'C/O SRINIVAS SANJEEV', status: 'Active' },
  { name: 'C/O SRINIVAS KISHORE', status: 'Active' },
  { name: 'C/O DR ANUPAMA P', status: 'Active' },
  { name: 'C/O SRINIVAS DANAIAH', status: 'Active' },
  { name: 'C/O SRINIVAS ASHOK DBR', status: 'Active' },
  { name: 'C/O TEJA DIAG', status: 'Active' },
  { name: 'C/O SRAVEN', status: 'Active' },
  { name: 'C/O SRINIVAS BLESSI', status: 'Active' },
  { name: 'C/O AIZAZ', status: 'Active' },
  { name: 'C/O RAMBABU', status: 'Active' },
  { name: 'C/O RAMBBABU', status: 'Active' },
  { name: 'C/O SRINIVAS RAMU', status: 'Active' },
  { name: 'C/O PRADEP', status: 'Active' },
  { name: 'C/O VALI', status: 'Active' },
  { name: 'C/O VALI,NARENDARE', status: 'Active' },
  { name: 'C/OSRINIVAS', status: 'Active' },
  { name: 'C/O ASHOK VARDHAN K', status: 'Active' },
  { name: 'C/O SRINIVAS NAVANEETHA', status: 'Active' },
  { name: 'C/O SRINIVAS DR PRAVEEN KUMAR', status: 'Active' },
  { name: 'C/O SRINIVAS VENKANNA', status: 'Active' },
  { name: 'c\\o srinivas', status: 'Active' },
  { name: 'C/O SRINIVAS SHIVA', status: 'Active' },
  { name: 'C/O SRINIVAS DR VIKAS', status: 'Active' },
  { name: 'C/O SRINIVAS MALLESH', status: 'Active' },
  { name: 'C/O SRINIVAS SIDDU', status: 'Active' },
  { name: 'MEGHA DIGE', status: 'Active' },
  { name: 'C/O VAMSHI KRISHNA', status: 'Active' },
  { name: 'KAMALA HOSPITAL', status: 'Active' },
  { name: 'SAHAARA HOSP', status: 'Active' },
  { name: 'C/O SRINIVAS MEGHA DIAGNOSTICS', status: 'Active' },
  { name: 'C/O J S HOSPITAL', status: 'Active' },
  { name: 'C/O JS HOSPITAL', status: 'Active' },
  { name: 'C/O VIJAY SRINIVAS', status: 'Active' },
  { name: 'C/O VIJAY METTU SRINIVAS', status: 'Active' },
  { name: 'C/O SRINIVAS VISWAS', status: 'Active' },
  { name: 'C/O SRI SAI DIAG', status: 'Active' },
  { name: 'C/O SRI SAI DIAG HYT', status: 'Active' },
  { name: 'C/O TANVI HOSP', status: 'Active' },
  { name: 'C/O TANVI HOSP RAMU', status: 'Active' },
  { name: 'C/O SHANKAR', status: 'Active' },
  { name: 'C/O SRINIVAS MAHESH', status: 'Active' },
  { name: 'C/O DR HIMA', status: 'Active' },
  { name: 'C/O DR VENKATESH', status: 'Active' },
  { name: 'C/O SHIVA SAGARI', status: 'Active' },
  { name: 'C/O SRI SAI SANJEEVANI DIAG', status: 'Active' },
  { name: 'C/O SRINIVAS VENKATA RAMANA', status: 'Active' },
  { name: 'C/O SRINIVAS VAMSHI LAB', status: 'Active' },
  { name: 'C/O SRINIVAS AJAZ CT', status: 'Active' },
  { name: 'C/O SRINIVAS GANESH LAB', status: 'Active' },
  { name: 'C/O SRINIVAS GOPI', status: 'Active' },
  { name: 'C/O JAGRUTHI HOSP', status: 'Active' },
  { name: 'C/I SRI VIJYA', status: 'Active' },
  { name: 'C/O SRI VIJYA', status: 'Active' },
  { name: 'C/O VANASTHALI HOSP', status: 'Active' },
  { name: 'C/O SRINIVAS SRI VIJAYA', status: 'Active' },
  { name: 'C/O SRINIVAS,GOPI', status: 'Active' },
  { name: 'C/O SRINIVAS, GOPI', status: 'Active' },
  { name: 'C/O BHAVYA HOSPITAL', status: 'Active' },
  { name: 'C/O SRIKARA HOSPITAL', status: 'Active' },
  { name: 'C/O SHIVA MANJUNATH CLINIC', status: 'Active' },
  { name: 'DR V PRABHAKAR', status: 'Active' },
  { name: 'C/O SRINIVAS POCHAMPALLY LINGASWAMY', status: 'Active' },
  { name: 'C/O SRINIVAS,NARESH', status: 'Active' },
  { name: 'C/O SRINIVAS NURSING STAFF', status: 'Active' },
  { name: 'C/O RAMANA', status: 'Active' },
  { name: 'C/O GK HOHP', status: 'Active' },
  { name: 'C/O SRINIVAS RAMANADBR', status: 'Active' },
  { name: 'C/O SRINIVAS APOLLO RAMESH', status: 'Active' },
  { name: 'C/O SRINIVAS STAFF NURSE', status: 'Active' },
  { name: 'C/O RAGHU SRINIVAS HOSPITAL', status: 'Active' },
  { name: 'C/O KAMALA HOSPITAL', status: 'Active' },
  { name: 'C/O AJAS', status: 'Active' },
  { name: 'C/O MANJUNATH CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS CHOUTUPPAL LINGASWAMY', status: 'Active' },
  { name: 'CO SRINIVAS', status: 'Active' },
  { name: 'C/O BANDLAHUDA THYROCARE MAHESH', status: 'Active' },
  { name: 'C/O SRINIVAS BHAVYA LAB SRIKANTH', status: 'Active' },
  { name: 'PRASIDHI HOSP', status: 'Active' },
  { name: 'C/O SRINIVAS GK HOSP', status: 'Active' },
  { name: 'DBR ASHOK', status: 'Active' },
  { name: 'C/O SAHAARA HOSP', status: 'Active' },
  { name: 'C/O SRINIVAS RAMESH', status: 'Active' },
  { name: 'C/O SRINIVAS RAMBABU', status: 'Active' },
  { name: 'C/O SRI VIJYA HOSP', status: 'Active' },
  { name: 'C/O SRINIVAS VENKANNA MRK', status: 'Active' },
  { name: 'C/O MEAGHA DIAG', status: 'Active' },
  { name: 'C/O SRINIVAS AIJAZ', status: 'Active' },
  { name: 'C/O SRINIVAS PRASIDHI NARESH', status: 'Active' },
  { name: 'C/O MANOGNA SHIVA', status: 'Active' },
  { name: 'C/O MAXI CURE SATHISH', status: 'Active' },
  { name: 'C/O PRAVEEN SIR', status: 'Active' },
  { name: 'C/O SRIKANTH', status: 'Active' },
  { name: 'C/O SRINIVAS RAGHU', status: 'Active' },
  { name: 'C/OI SRINIVAS', status: 'Active' },
  { name: 'C/O GIEETHA', status: 'Active' },
  { name: 'C/O SANJVANI', status: 'Active' },
  { name: 'C/o srinivas lingaswamy', status: 'Active' },
  { name: 'C/O SRINIVAS LINGASWAMY', status: 'Active' },
  { name: 'C/O SRINIVAS NAIDU SIR', status: 'Active' },
  { name: 'C/O GOPI,SRIKANTH', status: 'Active' },
  { name: 'C/O SRUTH', status: 'Active' },
  { name: 'C/O SRUTHI', status: 'Active' },
  { name: 'C/O SRINIVAS GIRI DRIVER', status: 'Active' },
  { name: 'C/O SRINIVAS NARESH', status: 'Active' },
  { name: 'C/O DBR ASHOK', status: 'Active' },
  { name: 'DR RAVINDER', status: 'Active' },
  { name: 'DBR SAJIDH', status: 'Active' },
  { name: 'DR MOUNIKA', status: 'Active' },
  { name: 'C/O SRINIVAS SURESH', status: 'Active' },
  { name: 'C/O SRINIVAS (PRASHANTH)', status: 'Active' },
  { name: 'C/O SRINIVAS PRASIDH REC', status: 'Active' },
  { name: 'C/O LINGA SWAMI', status: 'Active' },
  { name: 'C/O SRINIVAS SUNRIYASI RAMU', status: 'Active' },
  { name: 'C/O SRINIVAS ASIAN NAVEEN', status: 'Active' },
  { name: 'C/O SOWMYA DBR', status: 'Active' },
  { name: 'C/O SRINIVAS LAB NARESH', status: 'Active' },
  { name: 'C/O PRASIDH NARESH', status: 'Active' },
  { name: 'PRASIDH NARESH', status: 'Active' },
  { name: 'C/O SRINIVAS SRIKANTH', status: 'Active' },
  { name: 'C/O SRINIVSD', status: 'Active' },
  { name: 'C/O AMULYA LAB', status: 'Active' },
  { name: 'C/O GK DIVYA MADAM', status: 'Active' },
  { name: 'C/O KALYAN LAB', status: 'Active' },
  { name: 'C/O SRINU VEMAREDDY', status: 'Active' },
  { name: 'C/O SRINIVAS UMAKANTH', status: 'Active' },
  { name: 'C/OSRINIVAS891989659', status: 'Active' },
  { name: 'C/O SRINIVAS SUMANE MANOGNA HOSPITALE', status: 'Active' },
  { name: 'C/O GK SHIVA', status: 'Active' },
  { name: 'C/O GIRI', status: 'Active' },
  { name: 'C/O SRINIVAS SRIKANTH MAXI', status: 'Active' },
  { name: 'C/O MAXI CURE RANGA', status: 'Active' },
  { name: 'C/O NAVEEN ASIAN DIAG', status: 'Active' },
  { name: 'C/O DILIP REDDY', status: 'Active' },
  { name: '9550076131', status: 'Active' },
  { name: 'C/O NARESH MARKETING', status: 'Active' },
  { name: 'C/O DBR RAMANA RNH', status: 'Active' },
  { name: 'C/O SRIBNIVAS', status: 'Active' },
  { name: 'C/O SRINIVAS RAGAVENDARA', status: 'Active' },
  { name: 'C/O SRNIVAS', status: 'Active' },
  { name: 'C/O HARI KRISHNA', status: 'Active' },
  { name: 'C/O SIRNIVAS', status: 'Active' },
  { name: 'C/O SIRINIVAS', status: 'Active' },
  { name: 'C/O SRINIVAS9494942965', status: 'Active' },
  { name: 'C/O VEMA REDDY DIAG', status: 'Active' },
  { name: 'C/O SRINIVAS VEMA REDDY', status: 'Active' },
  { name: 'C/O SRINIVAS9052162484', status: 'Active' },
  { name: 'C/O SELF', status: 'Active' },
  { name: 'C/O VISWAS HOSP', status: 'Active' },
  { name: 'C/O ORANGE HOSPITAL RAMESH', status: 'Active' },
  { name: 'C/O MANJUNATH CLINIC SHIVA', status: 'Active' },
  { name: 'C/O RAMESH PRASIDE', status: 'Active' },
  { name: 'DR NARSIMHA CHOUTUPPAL', status: 'Active' },
  { name: 'C/O SRINIVAS PRABAKARE', status: 'Active' },
  { name: 'JANATHA POLY CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS PRABHAKAR', status: 'Active' },
  { name: 'C/O LAB DIVYA', status: 'Active' },
  { name: 'C/O SRINIVAS KOLUJU', status: 'Active' },
  { name: 'C/O SRINIVAS, DR SRIKANTH', status: 'Active' },
  { name: 'C/O VENAKANNA', status: 'Active' },
  { name: 'C/O SRINIVAS DR PRAMOD KUMAR', status: 'Active' },
  { name: 'C/O GK LINGA SWAMI', status: 'Active' },
  { name: 'C/O SRINIVAS SURESH AVIGNA', status: 'Active' },
  { name: 'C/O SRINIVAS VIJAYA', status: 'Active' },
  { name: 'C/ SRINIVAS', status: 'Active' },
  { name: 'C/O SRINIVAS parshuram', status: 'Active' },
  { name: 'C/O DBR RAMANA BASHA SAI', status: 'Active' },
  { name: 'C/O VENKANNA PADMA', status: 'Active' },
  { name: 'C/O KONNECT SURESH', status: 'Active' },
  { name: 'C/O SRINIVAS MAHESH TYROCARE', status: 'Active' },
  { name: 'C/O SRINIVAS DR GURUKRISHNA', status: 'Active' },
  { name: 'C/O SRINIVAS LATHIKA DIAGNGOSTICS', status: 'Active' },
  { name: 'C/O SRINIVAS DR VIJAY', status: 'Active' },
  { name: 'C/O SRINIVAS BHAVITHA DIAGNOSTIC CENTRE', status: 'Active' },
  { name: 'C/O SRINIVAS KALYAN LAB', status: 'Active' },
  { name: 'C/O SRINIVAS MEETU VIJAY SIR', status: 'Active' },
  { name: 'C/O SRINIVAS ARUN VENYA POLI CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS SUJATHA BHAVITH DIAG', status: 'Active' },
  { name: 'C/O SRINIVAS GK SHIVASHANKAR', status: 'Active' },
  { name: 'C/O SRINIVAS NAGESH', status: 'Active' },
  { name: 'C/O SRINIVAS MAX', status: 'Active' },
  { name: 'C/O SRINIVAS MAXI CURE HOSPITAL SATHESH', status: 'Active' },
  { name: 'C/O SRINIVAS MRK NARESH BRIJILKONE HOSPITAL', status: 'Active' },
  { name: 'C/O ASIAN DIAG NAVEEN', status: 'Active' },
  { name: 'C/O SRINIVAS APOLLO SATHISH', status: 'Active' },
  { name: 'C/O SRINIVAS DR MANJUNATH SIR CALL', status: 'Active' },
  { name: 'C/O DR PAVANI MANSOORABAD', status: 'Active' },
  { name: 'C/O DR VIKAS SIR CALL', status: 'Active' },
  { name: 'C/O DR VIJAY', status: 'Active' },
  { name: 'TANVI SRINIVAS', status: 'Active' },
  { name: 'C/O KRANTHI', status: 'Active' },
  { name: 'C/O SRINIVAS ELITE PHARMCY', status: 'Active' },
  { name: 'C/O MOTHER TERASA FD CLINIC KUNTLOOR', status: 'Active' },
  { name: 'VANASTHALI KISHORE', status: 'Active' },
  { name: 'CLO SRINIVAS', status: 'Active' },
  { name: 'C/O SRIKANTH HYT', status: 'Active' },
  { name: 'C/O SRINIVAS PRASIDH HOSPITAL RAJU', status: 'Active' },
  { name: 'C/O SRINIVAS FAHEEM', status: 'Active' },
  { name: 'C/O GK LINGA SWAMI BROTHER', status: 'Active' },
  { name: 'C/O SRINIVAS LINGA SWAMY VISHISHTA', status: 'Active' },
  { name: 'C/O SRINIVAS VIJAI', status: 'Active' },
  { name: 'C/O SRINIVAS HARI KRISHNA VANASTHALI', status: 'Active' },
  { name: 'C/O SRINIVASRAMANA', status: 'Active' },
  { name: 'C/O RAVI', status: 'Active' },
  { name: 'C/O RAVI ORANGE HOSPITAL', status: 'Active' },
  { name: 'C/O MALLESH', status: 'Active' },
  { name: 'C/O SRINIVAS CHETHANA RAMBABU', status: 'Active' },
  { name: 'C/O R S DIAGNOSTICS', status: 'Active' },
  { name: 'C/O GK HOSPITAL MOTHILAL', status: 'Active' },
  { name: 'C/O SRINIVAS DBR RAMANA', status: 'Active' },
  { name: 'C/O KISHORE VANASTHALI', status: 'Active' },
  { name: 'C/O SRINIVAS RAJU PRASIDE', status: 'Active' },
  { name: 'C/O NARESH VANASTHALI', status: 'Active' },
  { name: 'C/O KALAMMA', status: 'Active' },
  { name: 'C/O SRINIVAS RENUKA', status: 'Active' },
  { name: 'C/O SRINIVAS DR RENUKA BANDLAGUDA', status: 'Active' },
  { name: 'C/O SRINIVAS TA', status: 'Active' },
  { name: 'C/O SRINIVAS TANVI RAMU', status: 'Active' },
  { name: 'C/O SRINIVAS SHNKAR', status: 'Active' },
  { name: 'C/O SRINIVAS SHANKAR VANASTHALI', status: 'Active' },
  { name: 'C/O SURYA NARAYANA', status: 'Active' },
  { name: 'C/O SURYANARAYANA', status: 'Active' },
  { name: 'C/O HOME HOSPITAL', status: 'Active' },
  { name: 'C/O SRINIVAS GK MALLESH', status: 'Active' },
  { name: 'C/O SRINIVAS AYC POLY CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS DR ASLAM', status: 'Active' },
  { name: 'C/O SRINIVAS DR VIKAS CALL', status: 'Active' },
  { name: 'C/O SHIVA KRISHNA RECEP', status: 'Active' },
  { name: 'C/O APOLLO HOSPITALS', status: 'Active' },
  { name: 'C/O NAVANEETHA', status: 'Active' },
  { name: 'C/O SRINIVAS , OZONE MAHESH', status: 'Active' },
  { name: 'C/O PRASIDH HOSP RAJU', status: 'Active' },
  { name: 'SHARADHA EYE CARE MAMATHA', status: 'Active' },
  { name: 'C/O RAM BABU', status: 'Active' },
  { name: 'C/O SRINIVAS MATHRU SREE HOSPITAL', status: 'Active' },
  { name: 'C/O SRINIVAS AADHYA RAJU', status: 'Active' },
  { name: 'C/O SRINIVAS INSURANCE PURPUS', status: 'Active' },
  { name: 'C/O TANVI SRINU', status: 'Active' },
  { name: 'C/O SRINIVAS DR JANGEER', status: 'Active' },
  { name: 'C/O TARAMATHIPET', status: 'Active' },
  { name: 'C/O UNDUS SRAVAN', status: 'Active' },
  { name: 'C/O SRINIVAS SRIKANTH BHAVYA', status: 'Active' },
  { name: 'C/O SRINIVAS SAI GVK', status: 'Active' },
  { name: 'C/O SRINIVAS RAVI CLINIC', status: 'Active' },
  { name: 'ASIAN DIAGNOSTICS NAVEEN', status: 'Active' },
  { name: 'C/O SRINIVAS ASIAN DIAGNOSTICS NAVEEN', status: 'Active' },
  { name: 'C/O SRINIVAS R S DIAGNOSTICS', status: 'Active' },
  { name: 'C/O VENKATESH GOPI', status: 'Active' },
  { name: 'C/O SRTINIVAS', status: 'Active' },
  { name: 'C/O SRINIVAS DR SUSHMA', status: 'Active' },
  { name: 'C/O SRINIVAS DR NAGU', status: 'Active' },
  { name: 'C/O SRINIVAS SN DIAG', status: 'Active' },
  { name: 'C/O DANDUMAILARAM DR RAVI', status: 'Active' },
  { name: 'C/O SRINIVAS PARAMITHA RAJU', status: 'Active' },
  { name: 'C/O SRINIVAS DR M SRINIVAS ABDULAPUR MEETU', status: 'Active' },
  { name: 'C/O ALL INDIA LAB RAJU', status: 'Active' },
  { name: 'C/O SRINIVAS ANITHA SUN', status: 'Active' },
  { name: 'C/O MXC', status: 'Active' },
  { name: 'C/O SRINIVAS DR S ANJAIH', status: 'Active' },
  { name: 'C/O SRINIVAS TYROKYA', status: 'Active' },
  { name: 'C/O SRINIVAS TYROCARE DIAGNOSTICS MAHESH', status: 'Active' },
  { name: 'SRI BHAVYA DIAG SRIKANTH', status: 'Active' },
  { name: 'C/O VENKANNA MRKT', status: 'Active' },
  { name: 'C/O SRINIVAS MAXI CURE UDHAY', status: 'Active' },
  { name: 'C/O GOPI MAMATHA', status: 'Active' },
  { name: 'C/O SRINIVAS DR A RAJASEKHAR', status: 'Active' },
  { name: 'C/O SRINIVASDR A RAJASEKHAR', status: 'Active' },
  { name: 'C/O SRINIVAS SRI JANATHA DIAGNOSTICS', status: 'Active' },
  { name: 'C/O SRINIVAS NAGU MUNGANUR', status: 'Active' },
  { name: 'C/O MANJUNATH SIR', status: 'Active' },
  { name: 'C/O RAMESH MANJUNATH CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS SANTOSH', status: 'Active' },
  { name: 'C/O VIJAY METTU HOSPITAL', status: 'Active' },
  { name: 'C/O SRINIVAS ANUSHA', status: 'Active' },
  { name: 'C/O SRINIVAS VENKATESH.', status: 'Active' },
  { name: 'C/O SANJAY THIRUMALA DIAG', status: 'Active' },
  { name: 'C/O ELITE PHARMA', status: 'Active' },
  { name: 'C/IO BAV', status: 'Active' },
  { name: 'C/IO BHAVITHA DIAGNOSTICS', status: 'Active' },
  { name: 'SATHESH MUNGUNURE', status: 'Active' },
  { name: 'C/O SRINIVAS SRI JANATAHA POLY CLINIC', status: 'Active' },
  { name: 'C/O RAMESH APOLLO', status: 'Active' },
  { name: 'C/O SRINIVAS SRIDHAR RS DIAG', status: 'Active' },
  { name: 'C/O SRINIVAS IBRAHIM', status: 'Active' },
  { name: 'C/O SRINIVAS POCHAM PALLY BHANU DIAG', status: 'Active' },
  { name: 'C/O TIRUMALA DIAG', status: 'Active' },
  { name: 'C/O SRINIVAS DBR KRISHNA', status: 'Active' },
  { name: 'C/O LEGEND HOSPITAL', status: 'Active' },
  { name: 'C/O LINGA SWAMI VISISTA', status: 'Active' },
  { name: 'C/O DR MANSUR', status: 'Active' },
  { name: 'C/O SRINIVAS8688993502', status: 'Active' },
  { name: 'C/O JANANI POLY CLINIC', status: 'Active' },
  { name: 'C/0 SRINIVAS', status: 'Active' },
  { name: 'C/O PARASURAM SHADOW HOSPITAL', status: 'Active' },
  { name: 'DBR RAMANA / BASHA', status: 'Active' },
  { name: 'C/O KAYAN TEJA DIAG', status: 'Active' },
  { name: 'C/O ABDUL', status: 'Active' },
  { name: 'C/O GOPI NARESH BROTHER', status: 'Active' },
  { name: 'C/O DR P PANDU', status: 'Active' },
  { name: 'C/O DR M DURGA', status: 'Active' },
  { name: 'C/O SRINIVAS C/O KIRAN REDDY', status: 'Active' },
  { name: 'C/O VENKNT', status: 'Active' },
  { name: 'C/O SRINIVAS(DR HARIKA ENT CARE HOSPITAL)', status: 'Active' },
  { name: 'SUNSHINE', status: 'Active' },
  { name: 'ASHIAN SUNSHEN', status: 'Active' },
  { name: 'C/O SRINIVAS DR ANIL', status: 'Active' },
  { name: 'SRINIVAS SHIVA SANGI', status: 'Active' },
  { name: 'C/O SRINIVAS SHIVA SANGI', status: 'Active' },
  { name: 'SRINIVAS SHIVA NAGA RAJ', status: 'Active' },
  { name: 'C/O SRINIVAS SHIVA NAGA RAJ', status: 'Active' },
  { name: 'SRINIVAS NARESH MANJUNATH CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS PULSE NAYAK', status: 'Active' },
  { name: 'C/O VISWAS HOSP SRAVANITH', status: 'Active' },
  { name: 'C/O SRIINIVAS', status: 'Active' },
  { name: 'C/O ASIAN DIAGNOSTICS', status: 'Active' },
  { name: 'C/O DR YASHWANTH REDDY RADIOLOGIST', status: 'Active' },
  { name: 'C/O VIJAY CT', status: 'Active' },
  { name: 'C/O SRAVANTHI', status: 'Active' },
  { name: 'C/O SRINIVAS DR YADAGIRI', status: 'Active' },
  { name: 'C/O SRINIVAS DR PREM', status: 'Active' },
  { name: 'C/O RATHNAKER', status: 'Active' },
  { name: 'C/O RATHNAKER METTU', status: 'Active' },
  { name: 'AHSAN,MAJID', status: 'Active' },
  { name: 'C/O SRINIVAS THARMATHIPETA DR SUSHILA', status: 'Active' },
  { name: 'SRINI', status: 'Active' },
  { name: 'C/O PRAMODE KUMAR MANOGNA ABDULPER METTU', status: 'Active' },
  { name: 'C/O NARESH GK', status: 'Active' },
  { name: 'C/O KRANTHI LAB', status: 'Active' },
  { name: 'C/O RAJU TANVE', status: 'Active' },
  { name: 'C/O RAJU TANVI', status: 'Active' },
  { name: 'C/O GOPI NAVEEN', status: 'Active' },
  { name: 'C/O TIRUMALA DIAG SANJAY', status: 'Active' },
  { name: 'C/O VANASATLI HELATH CARE DIAG', status: 'Active' },
  { name: 'SRINJIVAS', status: 'Active' },
  { name: 'C/O SRINIVAS SURESH MAXI CURE', status: 'Active' },
  { name: 'SRINIVAS .VIJAY PRASIDH', status: 'Active' },
  { name: 'SRINIVAS , MALLESH', status: 'Active' },
  { name: 'SRINIVAS .SRILATHA AYYAMA', status: 'Active' },
  { name: 'SRINIVAS . GK NARESH', status: 'Active' },
  { name: 'SRINIVAS .ASIAN NAVEEN', status: 'Active' },
  { name: 'SRINIVAS . SRIKANTH', status: 'Active' },
  { name: 'SRINIVAS NAVNETHA', status: 'Active' },
  { name: 'SRINIVAS,PURUSHARAM', status: 'Active' },
  { name: 'SRINIVAS .PARSHURAM', status: 'Active' },
  { name: 'SRINIVAS, NITHYA SREE', status: 'Active' },
  { name: 'LIFE SPRING HOSPITAL', status: 'Active' },
  { name: 'SRINIVAS ,VIJAY', status: 'Active' },
  { name: 'SRINIVAS, SRINU', status: 'Active' },
  { name: 'SRINIVAS,JHANSI', status: 'Active' },
  { name: 'C/O RAVI TEJA', status: 'Active' },
  { name: 'C/O G NAGESHWAR REDDY', status: 'Active' },
  { name: 'SRINIVAS RAJU', status: 'Active' },
  { name: 'C/O GOPI SRIKANTH', status: 'Active' },
  { name: 'C/O TEJA DIAG KALYAN', status: 'Active' },
  { name: 'C/O SRINIVAS BALU', status: 'Active' },
  { name: 'C/O SHARAN HOSPITA PARSUAL', status: 'Active' },
  { name: 'C SRINIVAS SRAVAN KUMAR', status: 'Active' },
  { name: 'SRINIVAS,SHANKAR', status: 'Active' },
  { name: 'SRINIVAS,ASIAN NAVEEN', status: 'Active' },
  { name: 'SWAMY PARSURAMN', status: 'Active' },
  { name: 'C/O SRINIVAS DR SRAVANTHI', status: 'Active' },
  { name: 'C/O KRISHNA LAB', status: 'Active' },
  { name: 'C/O ABDUL CT TECH', status: 'Active' },
  { name: 'SRINIVAS RS DIG', status: 'Active' },
  { name: 'SRIDHAR RS DIAGNOSTICS', status: 'Active' },
  { name: 'SRINIVAS, MALESH', status: 'Active' },
  { name: 'SRINIVAS,NAVEEN ASIAN', status: 'Active' },
  { name: 'NAVEEN ASIAN', status: 'Active' },
  { name: 'BLESSY', status: 'Active' },
  { name: 'C/O AMMA HOSP', status: 'Active' },
  { name: 'SRINIVAS, NITHYA SANTHOSH SREE', status: 'Active' },
  { name: 'C/O SUNDHR RAMOGEE FLEMCIYT', status: 'Active' },
  { name: 'C/O SRINIVAS, VIJAY', status: 'Active' },
  { name: 'C/O REENUKA', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING', status: 'Active' },
  { name: 'C/O SHIVA GK HOSP', status: 'Active' },
  { name: 'C/O BALU', status: 'Active' },
  { name: 'C/O THYRO CARE MAHESH', status: 'Active' },
  { name: 'C/O PRASIDH STAFF', status: 'Active' },
  { name: 'C/O DR SUSHEELA GOWRELLI', status: 'Active' },
  { name: 'C/O GOPI RAGHU', status: 'Active' },
  { name: 'C/O SRINIVAS PEDDAMBUR', status: 'Active' },
  { name: 'C/O SRIKANTH MAXI CURE STAFF', status: 'Active' },
  { name: 'SHIVA SHANKAR', status: 'Active' },
  { name: 'PRAGMA SHIVA SHANKAR', status: 'Active' },
  { name: 'VANASTHALI HOSPITAL MAHESH', status: 'Active' },
  { name: 'C/O TYROCY', status: 'Active' },
  { name: 'C/O TYROCARE VALI', status: 'Active' },
  { name: 'C/O VENKATESH HOME HOSPATL', status: 'Active' },
  { name: 'C/O RAGU SRINIVAS HOSP', status: 'Active' },
  { name: 'C/O MAHESH OZEN HOSPITEL MARKEYTING', status: 'Active' },
  { name: 'C/O S N DIAG', status: 'Active' },
  { name: 'C/O SN DIAGNOSTICS VENOD', status: 'Active' },
  { name: 'C/O MOHAN', status: 'Active' },
  { name: 'SUNDHAR RAMOJI FILIM CITY', status: 'Active' },
  { name: 'C/O KONNECT JYOTHI', status: 'Active' },
  { name: 'C/O STAFF', status: 'Active' },
  { name: 'C/O DBR RAMANATYROKYA', status: 'Active' },
  { name: 'C/O TYROCARE RAVI', status: 'Active' },
  { name: 'C/O RAMA RAO SRINIVAS HOSP', status: 'Active' },
  { name: 'C/O POCHAM PALLI', status: 'Active' },
  { name: 'S2 WOMEN CARE CLINIC', status: 'Active' },
  { name: 'C/O ARINIVAS', status: 'Active' },
  { name: 'C/O Prasanna kumar prasidh Reception', status: 'Active' },
  { name: 'ROCK TOWN COLONY NAGOLE', status: 'Active' },
  { name: 'C/O SUMAN MANOGNA', status: 'Active' },
  { name: 'C/O KALYAN VANASTHALI', status: 'Active' },
  { name: 'CO/RAMBABU', status: 'Active' },
  { name: 'C/O GOPI JAYATH RAM OLD STAFF', status: 'Active' },
  { name: 'C\\O ARCHANA', status: 'Active' },
  { name: 'C/O BHANU VISWAS', status: 'Active' },
  { name: 'CO/DBR', status: 'Active' },
  { name: 'VENU ORANGE', status: 'Active' },
  { name: 'GVK HOSPITAL SAI', status: 'Active' },
  { name: 'C/O ARAVIND SRINIVAS', status: 'Active' },
  { name: 'C/O HEMA MEDAM', status: 'Active' },
  { name: 'C/O SHIVA SANKARE', status: 'Active' },
  { name: 'C/O GEETHA', status: 'Active' },
  { name: 'SRINIAS', status: 'Active' },
  { name: 'C/O MAHESH TYROKYA', status: 'Active' },
  { name: 'C/O MAHESH VANASTHALI LAB', status: 'Active' },
  { name: 'C/O SRIDHRE DRIVAR', status: 'Active' },
  { name: 'C/O DR RAJU BANJARA COLONY', status: 'Active' },
  { name: 'C/O MOHAMMAD DRIVARE', status: 'Active' },
  { name: 'C/O SRINIVAS7989603620', status: 'Active' },
  { name: 'C/ODR PRAVEEN KUMAR', status: 'Active' },
  { name: 'C/O JAGRUTHI HOSP MD', status: 'Active' },
  { name: 'C/O JYOTHI', status: 'Active' },
  { name: 'C/O choutuppal MALLESH', status: 'Active' },
  { name: 'C/O VASAVI MEDICAL HALL', status: 'Active' },
  { name: 'C/O VASU', status: 'Active' },
  { name: 'C/O VASU CT JUN', status: 'Active' },
  { name: 'C/O JS HOSTEL', status: 'Active' },
  { name: 'C/O JYOTHI TESLA', status: 'Active' },
  { name: 'C/O RANGA SIR', status: 'Active' },
  { name: 'C/O BHANU DIAG', status: 'Active' },
  { name: 'MAHALAXMI DIAGNOSTIC', status: 'Active' },
  { name: 'C/O SRINIVAS JNNARM COLONE', status: 'Active' },
  { name: 'C/O SRINIVAS MOTHILAL', status: 'Active' },
  { name: 'C/O SRI RAM', status: 'Active' },
  { name: 'PRASANA GK', status: 'Active' },
  { name: 'C/O SRINIVAS9177312832', status: 'Active' },
  { name: 'C/O MHESH OZEN', status: 'Active' },
  { name: 'C/O PARUSHURAM', status: 'Active' },
  { name: 'C/O MOTHILAL', status: 'Active' },
  { name: 'C/O JAITHRAM', status: 'Active' },
  { name: 'C/O ANWAR', status: 'Active' },
  { name: 'C/O PADMA SREE LAB', status: 'Active' },
  { name: 'C/O AIRA DIGNOSTICS', status: 'Active' },
  { name: 'C/O AAYAN DIGNOSTIC', status: 'Active' },
  { name: 'C/O AAYAN DIGNOSTICS', status: 'Active' },
  { name: 'C/O SRAVAN HYT', status: 'Active' },
  { name: 'C/O HARSHA OLD', status: 'Active' },
  { name: 'C/O HARSHA OLD AGE HOME', status: 'Active' },
  { name: 'C/O SURESH VIJAYA HOSPITAL', status: 'Active' },
  { name: 'C/O JOHNNY DIGNOSTICS', status: 'Active' },
  { name: 'C/O SWAMY HYT', status: 'Active' },
  { name: 'C/O AADHYA RAJU MD', status: 'Active' },
  { name: 'C/O NITHYA SREE', status: 'Active' },
  { name: 'C/O TELSA JYOTHI', status: 'Active' },
  { name: 'C/O THYRO CARE SAI', status: 'Active' },
  { name: 'C/O SOWAM DBR', status: 'Active' },
  { name: 'C/O DR VENISHA', status: 'Active' },
  { name: 'C/O DR VINISHA', status: 'Active' },
  { name: 'C/O ADRUTHI DIGNOSTIC', status: 'Active' },
  { name: 'C/O PAVAN LEGEND HOSPITAL', status: 'Active' },
  { name: 'C/O R', status: 'Active' },
  { name: 'C/O TANVI HEMA', status: 'Active' },
  { name: 'C/O RAVI TEJA PRAVEEN SIR', status: 'Active' },
  { name: 'SURESH KONNECT DIAG', status: 'Active' },
  { name: 'C/O BALAJI SUJATHA HOSPITAL RAVI TEJA', status: 'Active' },
  { name: 'C/O VIJAY SIR', status: 'Active' },
  { name: 'C/O RAVI TEJA SHEKAR YADAV', status: 'Active' },
  { name: 'C/O HARISH ABS NEURO MANEGER', status: 'Active' },
  { name: 'C/O RAJINI', status: 'Active' },
  { name: 'C/O VINOD CHETHANA HOSPITAL', status: 'Active' },
  { name: 'C/O JYOTHI DIAG', status: 'Active' },
  { name: 'C/O MAXI CURE RAJASHKARE', status: 'Active' },
  { name: 'C/O SATHISH NEELADRI HOSPITAL', status: 'Active' },
  { name: 'C/O VIJAY PRASID', status: 'Active' },
  { name: 'C/O RAVI TEJA DR VIKAS', status: 'Active' },
  { name: 'C/O PRASHANTH NEELADRI HOSPITAL', status: 'Active' },
  { name: 'C/O MAHOMAD DRIVER', status: 'Active' },
  { name: 'C/O PRAVEEN DBR', status: 'Active' },
  { name: 'C/O RAVI TEJA DR RAMU', status: 'Active' },
  { name: 'C/O KRISHNA VENI HOSPITAL MOD', status: 'Active' },
  { name: 'C/O RS D', status: 'Active' },
  { name: 'C/O RS DIAGNOSTICS SRIDHAR', status: 'Active' },
  { name: 'C/O JACKY SUNRISE', status: 'Active' },
  { name: 'C/O CURE DIGNOSTIC', status: 'Active' },
  { name: 'C/O DR JYOTHI VIJAYA HOSPITAL', status: 'Active' },
  { name: 'C/O SRINIVAS,mahesh', status: 'Active' },
  { name: 'C/O SRINIVAS RAJA MALIKE', status: 'Active' },
  { name: 'C/O SRINIVAS RAJA MALIK LAXMA REDDY PALEM', status: 'Active' },
  { name: 'C/O ASHOK DBR', status: 'Active' },
  { name: 'C/O THRUDIN', status: 'Active' },
  { name: 'C/O VENU KUMARE', status: 'Active' },
  { name: 'C/O VENKNT PRASIDE', status: 'Active' },
  { name: 'C/O REKHA DIGNOSTICS HYT', status: 'Active' },
  { name: 'JAKKI SIR', status: 'Active' },
  { name: 'C/O SHANKAR PRAGMA HOSPITAL', status: 'Active' },
  { name: 'C/O GK PRASANNA', status: 'Active' },
  { name: 'C/O DR SANTHOSH', status: 'Active' },
  { name: 'C/O DR SANTHOSH RAMANA', status: 'Active' },
  { name: 'C/O BALU SRINIVAS', status: 'Active' },
  { name: 'C/O GK IP BILLING STAFF', status: 'Active' },
  { name: 'C/O ORANGE HOSPITAL AMRUTHA', status: 'Active' },
  { name: 'C/O MAXI CURE RAJASHEKAR SRINIVAS', status: 'Active' },
  { name: 'C/O GOPI PRAGMA LAB', status: 'Active' },
  { name: 'DRMAHESH POCHAMPALLY', status: 'Active' },
  { name: 'C/O RAMESH OREANG', status: 'Active' },
  { name: 'C/O RAMESH ORANGE HOSPITALS', status: 'Active' },
  { name: 'C/O DIVYA MADAM', status: 'Active' },
  { name: 'C/O GK HOHPGURUKRISHNA SIR', status: 'Active' },
  { name: 'C/O GK HOHP GURUKRISHNA SIR', status: 'Active' },
  { name: 'C/O SN DIAGNOSTICS SAJID', status: 'Active' },
  { name: 'C/O PRATHAP RMP', status: 'Active' },
  { name: 'C/O LAB RAMESH', status: 'Active' },
  { name: 'DR GURU KRISHNA', status: 'Active' },
  { name: 'C/O SUNRISE HOSPITAL JAKKI', status: 'Active' },
  { name: 'C/O BHAVANI DIAG SANJAI', status: 'Active' },
  { name: 'C/OSRIDHAR ORANGE', status: 'Active' },
  { name: 'C/O DR AMAR GOUD ORANGE RMO', status: 'Active' },
  { name: 'C/O SRINIVAS LINE DIAGNOSTICS', status: 'Active' },
  { name: 'SWECHA OPITICALS SANDEEP', status: 'Active' },
  { name: 'C/O RAJANI', status: 'Active' },
  { name: 'C/O JAYATH RAM', status: 'Active' },
  { name: 'C/O RMP SAI', status: 'Active' },
  { name: 'C/O PARVATHI', status: 'Active' },
  { name: 'Appolo shiva', status: 'Active' },
  { name: 'C/O APOLLO SHIVA', status: 'Active' },
  { name: 'C/O RAVI TEJA DR P MALLA REDDY', status: 'Active' },
  { name: 'C/O DR P MALLA REDDY', status: 'Active' },
  { name: 'C/O NAVEEN PRAGMA', status: 'Active' },
  { name: 'C/O NAVEEN PRGMA', status: 'Active' },
  { name: 'RAJ KIRAN', status: 'Active' },
  { name: 'C/O RAVI TEJA DR MURALI GOUD CALL', status: 'Active' },
  { name: 'C/O RAVI TEJA SRI SOWMYA MKT', status: 'Active' },
  { name: 'C/O RAVI TEJA RAJASHEKAR', status: 'Active' },
  { name: 'C/O PRADEEP HOS MD', status: 'Active' },
  { name: 'C/O DR DIVYA GK HOSP', status: 'Active' },
  { name: 'C/O ANUSHA AAYAN LAB', status: 'Active' },
  { name: 'C/O VANASTALI DIAGNOSTICS', status: 'Active' },
  { name: 'CLO SHARAVAN SRI SRINIVASA MEDICALS', status: 'Active' },
  { name: 'C/O DR ANOOP', status: 'Active' },
  { name: 'C/O DR SRINIVAS PEDDAMBERPET', status: 'Active' },
  { name: 'C/O VENKAT PRASIDE', status: 'Active' },
  { name: 'C/O TULASIRAM STAFF VIVERA', status: 'Active' },
  { name: 'C/O AIRA MADHU KIRAN', status: 'Active' },
  { name: 'C/O LINGA SWAMI GK HOSP', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING RAJU HAYAGREEVA', status: 'Active' },
  { name: 'C/O KARTHIK HAYATHNAGAR', status: 'Active' },
  { name: 'C/O SRINIVASA', status: 'Active' },
  { name: 'C/O RAM KOTI LEGEND HOSPITAL', status: 'Active' },
  { name: 'SRILATHA...', status: 'Active' },
  { name: 'C/O SHANKAR NEW AMMA CLINIC', status: 'Active' },
  { name: 'C/O RAJU PRASIDI', status: 'Active' },
  { name: 'C/O NAGARANI', status: 'Active' },
  { name: 'C/O SRIRAM', status: 'Active' },
  { name: 'C/O MAHESH DILSUKNAGAR', status: 'Active' },
  { name: 'C/O RAVI GK HOSPITAL', status: 'Active' },
  { name: 'C/O SURENDER REDDY', status: 'Active' },
  { name: 'C/O SAI PRASIDH HOSPITAL', status: 'Active' },
  { name: 'C/O NAGESHWAR REDDY PRASIDH HOSPITAL', status: 'Active' },
  { name: 'C/O SHANKAR MAATHRUSRI HOSPITAL', status: 'Active' },
  { name: 'C\\O LAVA', status: 'Active' },
  { name: 'C/O VAMSI LAB', status: 'Active' },
  { name: 'C/O DR ZIKKI SIR SUNRISE HOSPITAL', status: 'Active' },
  { name: 'C/O DR RAJKUMAR SUNRISE HOSPITAL', status: 'Active' },
  { name: 'C/O NANDHINI PRASIDI HOSPITAL', status: 'Active' },
  { name: 'C/O ARUNA CHETHANA HOSPITAL', status: 'Active' },
  { name: 'C/O NAVEEN SRI RAM', status: 'Active' },
  { name: 'C/O DRKARTHIK ORANGE', status: 'Active' },
  { name: 'C/O DR KARTHIK ORANGE', status: 'Active' },
  { name: 'C/O DR MAHESH POCHAMPALLI', status: 'Active' },
  { name: 'C/O DR MALLESH POCHAMPALLI', status: 'Active' },
  { name: 'C/O NAGARAJU CITI MED HOSPITAL', status: 'Active' },
  { name: 'C/O SAI SANJEVANI LAB HYT', status: 'Active' },
  { name: 'ICONIC', status: 'Active' },
  { name: 'C/O DR RAKESH', status: 'Active' },
  { name: 'C/O DR HARSHA', status: 'Active' },
  { name: 'DR VEENISHA', status: 'Active' },
  { name: 'C/O BHAVYA DIAG', status: 'Active' },
  { name: 'C/O MANOGNA HOSPITAL', status: 'Active' },
  { name: 'C/O BHOOPAL', status: 'Active' },
  { name: 'C/O ASHA WORKER', status: 'Active' },
  { name: 'C/O SABITHA ASHA WORKER', status: 'Active' },
  { name: 'C/O RAJASHEKAR JANATHA DIAGNOSTICS', status: 'Active' },
  { name: 'C/O MAHESH PRAGMA', status: 'Active' },
  { name: 'C/O DR ARUNA JYOTHI', status: 'Active' },
  { name: 'PRAGMA PARVATHI', status: 'Active' },
  { name: 'C/O RAVI TEJA DR RAMULU', status: 'Active' },
  { name: 'C/O DR MOHAN', status: 'Active' },
  { name: 'C/O JAGAN RAVI TEJA', status: 'Active' },
  { name: 'KRISHNA LAB DBR', status: 'Active' },
  { name: 'C/O KARTHIK PRASID', status: 'Active' },
  { name: 'BHASAKR MEDICAL SHOP VANASTALI', status: 'Active' },
  { name: 'BHASAKR MEDICAL SHOP VANASTALI RAVI TEJA', status: 'Active' },
  { name: 'C/O VENKAT LAB', status: 'Active' },
  { name: 'SPRINT NARESH', status: 'Active' },
  { name: 'C/O SRILATHA', status: 'Active' },
  { name: 'C/O DR VENKATESHWARLU', status: 'Active' },
  { name: 'C/O SRIKANTH RAVI TEJA', status: 'Active' },
  { name: 'C/O RAJITHA SAHARA HOSPITAL', status: 'Active' },
  { name: 'C/O SRINIVAS GANESH..', status: 'Active' },
  { name: 'PRAGMA NAVEEN', status: 'Active' },
  { name: 'C/O PRAGMA HARISH', status: 'Active' },
  { name: 'C/O OREIANTAL POLY CLINIC HAYATHNAGAR', status: 'Active' },
  { name: 'C/O KRISHNA ORANGE HOSPITAL', status: 'Active' },
  { name: 'C/O NARESH SPRINT DIAG', status: 'Active' },
  { name: 'ANU..', status: 'Active' },
  { name: 'ORANGE MAHESH', status: 'Active' },
  { name: 'C/O AISHAN', status: 'Active' },
  { name: 'SHADOW GEETHA', status: 'Active' },
  { name: 'RADHIKA MADAM', status: 'Active' },
  { name: 'C/O DR PADMA SHAMALA', status: 'Active' },
  { name: 'C/O AKHILA MADAM', status: 'Active' },
  { name: 'LIONS DIAG', status: 'Active' },
  { name: 'C/O LINGA SWAMY BROTHER', status: 'Active' },
  { name: 'C/O SURENDAR REDDY APOLLO', status: 'Active' },
  { name: 'C/O SADYA SISTER', status: 'Active' },
  { name: 'C/O RAJASHEKAR NEELADRI HOSPITAL', status: 'Active' },
  { name: 'C/O USHA MAXI CURE', status: 'Active' },
  { name: 'C/O SRI LAKSHMI BONE SETTING CENTER', status: 'Active' },
  { name: 'C/O RAVI TEJA DR AJAY RMP G SCHOOL', status: 'Active' },
  { name: 'C/O MEDQUIST SHEKAR', status: 'Active' },
  { name: 'SHRAVAN', status: 'Active' },
  { name: 'C/O DIVYA LAB', status: 'Active' },
  { name: 'C/O SPRINT DIAG', status: 'Active' },
  { name: 'C/O PRAVEEN LAB DBR', status: 'Active' },
  { name: 'C/O RAJU ARUNA HOSPITAL', status: 'Active' },
  { name: 'C/OMAHESH VANASTHALI HOSPATAL', status: 'Active' },
  { name: 'C/O SRIKANTH RAGHU', status: 'Active' },
  { name: 'C/O SPRINT NAVEEN', status: 'Active' },
  { name: 'C/O NAVEEN.', status: 'Active' },
  { name: 'SRIDHAR PRAGMA CT TEC', status: 'Active' },
  { name: 'DR SANDEEP', status: 'Active' },
  { name: 'C/O G N REDDY PRASIDH HOSPITAL', status: 'Active' },
  { name: 'C/O APOLLO SURENDAR', status: 'Active' },
  { name: 'C/O ASHWINI SISTER', status: 'Active' },
  { name: 'C/O BALU MATHRUSRI', status: 'Active' },
  { name: 'SRAVAN MEDICAL SHOP AUTO NAGAR', status: 'Active' },
  { name: 'THYROCARE HYT', status: 'Active' },
  { name: 'C/O RAVI TEJA RAMA KRISHNA', status: 'Active' },
  { name: 'C/O RAVI TEJA S,V DIGNOSTICS', status: 'Active' },
  { name: 'C/O DR TARUN', status: 'Active' },
  { name: 'C/O SRINVAS', status: 'Active' },
  { name: 'C/O NAGESH LAB SREYANSH SCAN CENTER', status: 'Active' },
  { name: 'MAXI CURE PRASHANTH', status: 'Active' },
  { name: 'C/O CHAITHANYA DIAGNOSTICS', status: 'Active' },
  { name: 'C/O LAVA KUMAR', status: 'Active' },
  { name: 'SHIVA ...PT STAFF', status: 'Active' },
  { name: 'DR DIVYA DEVI', status: 'Active' },
  { name: 'C/O RAVI TEJA / RAMAKRISHNA BANDLA GUDA', status: 'Active' },
  { name: 'C/O BAVITHA DIAG', status: 'Active' },
  { name: 'C/O SRAVAN.', status: 'Active' },
  { name: 'C/O LINGA SWAMI KRUTHIKA HOSPITAL', status: 'Active' },
  { name: 'RENOVA PHARMACY', status: 'Active' },
  { name: 'C/O RAVI TEJA RAJU', status: 'Active' },
  { name: 'C/O SURESH NEELADRI', status: 'Active' },
  { name: 'SUDHIR CHETHANA HOSPITAL', status: 'Active' },
  { name: 'C/O SHANKAR PRASIDHI DRIVER', status: 'Active' },
  { name: 'C/O ABISHEK PRGMA', status: 'Active' },
  { name: 'C/O RAJESH MARKETING', status: 'Active' },
  { name: 'C/O PRAGMA GOPI', status: 'Active' },
  { name: 'C/O SRI SOWMYA HOSPITAL SRIKANTH', status: 'Active' },
  { name: 'C/O DR NARESH POCHAMPALLI', status: 'Active' },
  { name: 'C/O MAXI CURE DRIVER BUNTTY', status: 'Active' },
  { name: 'C/O VIJAY CT TEC LAKSHMI HOSPITAL', status: 'Active' },
  { name: 'C/O MAHESH...', status: 'Active' },
  { name: 'C/O MED LIFE DIAG', status: 'Active' },
  { name: 'Dr Geetha shadow hospital', status: 'Active' },
  { name: 'C/O DR SWATHI REDDY MANOGNA HOSPITAL', status: 'Active' },
  { name: 'C/O JANARDHAN VISWAS', status: 'Active' },
  { name: 'C/ODR SWETHA KIRAN', status: 'Active' },
  { name: 'C/O VIJAY LAB PRASIDHI', status: 'Active' },
  { name: 'C/O APOLLO DIAGNOSTICS', status: 'Active' },
  { name: 'C/O SAI SANJEEVANI HOSPITAL DOCTOR', status: 'Active' },
  { name: 'C/O NAVEEN SRI RAM BROTHER', status: 'Active' },
  { name: 'C/O SRINIVAS GK HOUSE KEEPING', status: 'Active' },
  { name: 'C/O PRAGMA STAFF', status: 'Active' },
  { name: 'C/O NURSING STAFF', status: 'Active' },
  { name: 'LIFE LINE DIAG RAVI TEJA', status: 'Active' },
  { name: 'C/O S N DIAG VINOD', status: 'Active' },
  { name: 'C/O IQONK', status: 'Active' },
  { name: 'C/O VENKAT OM HOSPITAL', status: 'Active' },
  { name: 'C/O CHANDANA SISTER PRAGMA STAFF', status: 'Active' },
  { name: 'BHASKAR SUJATHA HOSPITAL', status: 'Active' },
  { name: 'C/O ASHOK PRASIDH', status: 'Active' },
  { name: 'ANUKRA DIAH HYT', status: 'Active' },
  { name: 'C/O NITHIN LAB', status: 'Active' },
  { name: 'C/O SHIVA OMNI HOSPITAL', status: 'Active' },
  { name: 'C/O PREGMA MOD', status: 'Active' },
  { name: 'B .RAVI', status: 'Active' },
  { name: 'C/O RAVI SHANKER', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING SHANKAR', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING SHANKAR LIFE LINE DIAG', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING Shanker LIFE LINE DIAG', status: 'Active' },
  { name: 'C/O MONA PRASIDHI', status: 'Active' },
  { name: 'C/O B. RAVI', status: 'Active' },
  { name: 'C/O RAVI MARKETING', status: 'Active' },
  { name: 'C/O LINGA SWAMY NEELADRI HOSPITAL DRIVER', status: 'Active' },
  { name: 'C/O SHIVA SBG DIAGNOSTICS', status: 'Active' },
  { name: 'C/O SHEELA', status: 'Active' },
  { name: 'C/O PRASIDHI ANAND', status: 'Active' },
  { name: 'CURE DIAGNOSTIC', status: 'Active' },
  { name: 'C/O HARISH AMBULANCE PRASIDH', status: 'Active' },
  { name: 'PREAM', status: 'Active' },
  { name: 'DR PRAME', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING PADMASRI DIAG', status: 'Active' },
  { name: 'C/O DR UMAKANTH SUNRAYS HOSPITAL KUNTLOOR', status: 'Active' },
  { name: 'C/O RAJU CHETHANA HOSPITAL', status: 'Active' },
  { name: 'C/O RAMU SIR', status: 'Active' },
  { name: 'JS STAFF', status: 'Active' },
  { name: 'DR SURESH SHADOW HOSPITAL', status: 'Active' },
  { name: 'DR KISHORE SHADOW HOSPITAL', status: 'Active' },
  { name: 'C/O DR K BHARGAVI', status: 'Active' },
  { name: 'C/O TANGARILLA HOUSE', status: 'Active' },
  { name: 'HARI KRISHNA VANASATHLI HELATH CARE', status: 'Active' },
  { name: 'C/O LIFE LINE DIAG', status: 'Active' },
  { name: 'C/O SRI DIVYA DIAG', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING BHSKARE MEDICAL', status: 'Active' },
  { name: 'R SUDHAKAR', status: 'Active' },
  { name: 'SHANKAR LINGA SWAMY', status: 'Active' },
  { name: 'SHADOW HOSPITAL HAYATH NAGAR', status: 'Active' },
  { name: 'AILAIAH', status: 'Active' },
  { name: 'DBR RAMANA RAVI DIAG', status: 'Active' },
  { name: 'C/O SHEKAR NAGENDHAR SIR CILNIC', status: 'Active' },
  { name: 'C/O RANGA MAXCURU', status: 'Active' },
  { name: 'C/O VANASTHALI HOSP D M', status: 'Active' },
  { name: 'C/O GURU KRISHNA SIR', status: 'Active' },
  { name: 'DR RAMA KRISHNA BANDALAGUDA', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING SRIKANTH', status: 'Active' },
  { name: 'C/O PARASURAM..', status: 'Active' },
  { name: 'C/O VASANTHA CHINMAY', status: 'Active' },
  { name: 'C/O MADHAVI LAKSHMI HELATH CARE', status: 'Active' },
  { name: 'C/O CHALAPATHI', status: 'Active' },
  { name: 'C/O DR GOPINADH DESHMUKH', status: 'Active' },
  { name: 'C/O DR GOPINATH DESHMUK', status: 'Active' },
  { name: 'C/O UDAY NEELADRI HOSPITAL', status: 'Active' },
  { name: 'C/O ANKURA DIAGNOSTICS', status: 'Active' },
  { name: 'C/O RAGHU HYT', status: 'Active' },
  { name: 'C/O I JANATHA DIAGNOSTICS', status: 'Active' },
  { name: 'C/O SRINIVASA MEDICAL SHOP', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING RAVI', status: 'Active' },
  { name: 'C/O LAKSHMI HEALTH CARE', status: 'Active' },
  { name: 'C/O SRAVAN PLUS', status: 'Active' },
  { name: 'C/O SRIDHAR SRI SAI POLY CLINC DR AJAY', status: 'Active' },
  { name: 'C/O DR NARESH..', status: 'Active' },
  { name: 'C/O NEELADRI HOSPITAL', status: 'Active' },
  { name: 'ANVESH AAYUSH HOSPITAL', status: 'Active' },
  { name: 'C/O GK STAFE', status: 'Active' },
  { name: 'C/O VALI TYROCARE DIAGNOSTICS HYT', status: 'Active' },
  { name: 'C/O ABDHUL CT ENG', status: 'Active' },
  { name: 'C/O REDDYA NAIK', status: 'Active' },
  { name: 'C/O JANU DIAG', status: 'Active' },
  { name: 'C/O JONNY DIAGNOSTIC & POLY CLINIC', status: 'Active' },
  { name: 'C/O SRI TULAJA DIAGNOSTICS', status: 'Active' },
  { name: 'C/O SANTHOSH LAB TEC', status: 'Active' },
  { name: 'C/O NAVEEN PRASIDH', status: 'Active' },
  { name: 'C/O HARI SHNKAR', status: 'Active' },
  { name: 'C/O SRAVANTHI SRI CINMY', status: 'Active' },
  { name: 'C/O SANTHOSH VISWAS HOSPITAL', status: 'Active' },
  { name: 'C/O SATHISH CHARISHMA MEDICALS', status: 'Active' },
  { name: 'C/O SONTHOSH VISWAS', status: 'Active' },
  { name: 'C/O YAMINI', status: 'Active' },
  { name: 'C/O PRAKASH', status: 'Active' },
  { name: 'C/O VISWAS PRAKASH', status: 'Active' },
  { name: 'C/O VINAY KOTA', status: 'Active' },
  { name: 'DR VINAY KOTA', status: 'Active' },
  { name: 'C/O RAVITEJA SRAVAN LAB', status: 'Active' },
  { name: 'VENKATESH OLD REC', status: 'Active' },
  { name: 'C/O GOUTHAM ABHAYA HOSPITAL', status: 'Active' },
  { name: 'C/O ANITHA', status: 'Active' },
  { name: 'C/O SELF RMP', status: 'Active' },
  { name: 'C/O ORANGE AMRUTHA', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING DR VIKAS SIR CALL', status: 'Active' },
  { name: 'DR GURU SIR', status: 'Active' },
  { name: 'C/O RAVI DRIVAR', status: 'Active' },
  { name: 'C/O SRIKANTH REDDY', status: 'Active' },
  { name: 'C/O V9 REPORTER', status: 'Active' },
  { name: 'C/O CURE DIGNOSTIC TAJ SHAFI', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING CAII TO DR NAGU SIR', status: 'Active' },
  { name: 'C/O CHANDU RAVI TEJA', status: 'Active' },
  { name: 'DR T SURESH', status: 'Active' },
  { name: 'C/O SIRAJ', status: 'Active' },
  { name: 'C/O SRIDHAR. DR AJAY', status: 'Active' },
  { name: 'C/O MHADU AIRA', status: 'Active' },
  { name: 'C/O SAI SANJEEVANI HOSPITAL SRI RAM', status: 'Active' },
  { name: 'GK NARESH DR JHANSI RMP', status: 'Active' },
  { name: 'C/O MAXI CURE MANAGAR', status: 'Active' },
  { name: 'C/O NAVEEN POCHAMPALLI', status: 'Active' },
  { name: 'C/O RAMESH SAHARA', status: 'Active' },
  { name: 'C/O SAI RAMA', status: 'Active' },
  { name: 'C/O SURYA CLINIC', status: 'Active' },
  { name: 'C/O SRINIVAS RAJU AASHYA', status: 'Active' },
  { name: 'C/O CITY MEDE', status: 'Active' },
  { name: 'C/O DR MAMATHA', status: 'Active' },
  { name: 'C/O CHARAN GEVAN SAI HOSPITAL', status: 'Active' },
  { name: 'C/O PRABHU VARDHAN PRADISIDI', status: 'Active' },
  { name: 'C/O SRINIVAS S2 DIAGNOSTICS', status: 'Active' },
  { name: 'C/O VIGNESH', status: 'Active' },
  { name: 'C/O ORANGE STAFF', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING P RAMAKRISHNA BUNDL GUDHA', status: 'Active' },
  { name: 'C/O DR SANJAY KUMAR GK HOSPITAL', status: 'Active' },
  { name: 'C/O SRINIVAS MAHESH DILSUNAGAR', status: 'Active' },
  { name: 'C/O RAJEEV', status: 'Active' },
  { name: 'LION DIAG', status: 'Active' },
  { name: 'C/O ORANGE HOSPITAL ARCHANA', status: 'Active' },
  { name: 'SIRISHA', status: 'Active' },
  { name: 'C/O VIJAYA HOSPITAL METTU', status: 'Active' },
  { name: 'C/O KAVITHA', status: 'Active' },
  { name: 'C/O KAVITHA VEMA REDDY', status: 'Active' },
  { name: 'C/O VENKATESH PRASIDH', status: 'Active' },
  { name: 'C/O VANASHALI NARESH', status: 'Active' },
  { name: 'C/O RAVITEJA/ HARIKA DIAGNOSTIC', status: 'Active' },
  { name: 'C/O SIRISHA MADAM', status: 'Active' },
  { name: 'C/O SRIDHAR SRI SAI HOSPITAL', status: 'Active' },
  { name: 'VISWAS SANTHOSH', status: 'Active' },
  { name: 'C/O BHALU', status: 'Active' },
  { name: 'C/O V SRINIVAS', status: 'Active' },
  { name: 'C/O SWATHI', status: 'Active' },
  { name: 'NDC', status: 'Active' },
  { name: 'C/O SUPRJA HOSPITAL', status: 'Active' },
  { name: 'C/O BHALU HYT', status: 'Active' },
  { name: 'C/O BALU HYT', status: 'Active' },
  { name: 'C/O SHIVA OREANG', status: 'Active' },
  { name: 'C/O G RAVI TEJA', status: 'Active' },
  { name: 'C/O SIDDU MOD PRAGMA', status: 'Active' },
  { name: 'C/O JK SHIVA', status: 'Active' },
  { name: 'C/O SURSH', status: 'Active' },
  { name: 'C/O RAVITEJA MARKETING PARUSHURAM', status: 'Active' },
  { name: 'C/O BHANU SIR', status: 'Active' },
  { name: 'C/O SRIDHAR PARGMA', status: 'Active' },
  { name: 'C/O SATHISH MAXI CURE STAFF', status: 'Active' },
  { name: 'C/O SATHISH MAXI CURE', status: 'Active' },
  { name: 'C/ODR SANDEEP', status: 'Active' },
  { name: 'C/O DR RAMESH', status: 'Active' },
  { name: 'C/O NAVEEN KRISHNA VENI HOSPITAL', status: 'Active' },
  { name: 'C/O SHRAVAN LAB', status: 'Active' },
  { name: 'DBR SOWMYA', status: 'Active' },
  { name: 'C/O VIJAY CT TEC...', status: 'Active' },
  { name: 'C/O BLESY PRASIDH', status: 'Active' },
  { name: 'C/O DR SELF', status: 'Active' },
  { name: 'C/O SRI LAKSHMI VINAYAKA MEDICAL & GENERAL STORES', status: 'Active' },
  { name: 'C/O VEERA SWAMY', status: 'Active' },
  { name: 'C/O THANVI SRINU', status: 'Active' },
  { name: 'C/O KOUSHIK', status: 'Active' },
  { name: 'C/O RATHNAKAR 9959492502', status: 'Active' },
  { name: 'C/O THANVI RAMU', status: 'Active' },
  { name: 'C/O DBR VIJJAYA', status: 'Active' },
  { name: 'C/O BHASKAR', status: 'Active' },
  { name: 'C/O DR IBRAHIM', status: 'Active' },
  { name: 'C/O NARENDAR', status: 'Active' },
  { name: 'C/O MANJULA', status: 'Active' },
  { name: 'C/O RAJITHA..', status: 'Active' },
  { name: 'C/O PRASHURAM', status: 'Active' },
  { name: 'C/O DR RAJ KUMAR', status: 'Active' },
  { name: 'C/O DR MOUNIKA REDDY', status: 'Active' },
  { name: 'C/O RAVI TEJA KATTA RAJU', status: 'Active' },
  { name: 'C/O PRATHAP MEETU', status: 'Active' },
  { name: 'C/O AADHYA SRAVAN', status: 'Active' },
  { name: 'MEDIC DIAGNOSTIC', status: 'Active' },
  { name: 'M SRINIVAS MEDIC DIAGNOSTIC', status: 'Active' },
  { name: 'C/O RAVITEJA DR ESHWAR', status: 'Active' },
  { name: 'ANITHA SUNRICE', status: 'Active' },
  { name: 'C/O DR SHIRISHA', status: 'Active' },
  { name: 'PRASIDH VIJAY LAB', status: 'Active' }
];

async function main() {
  console.log(`Seeding sources...`);
  
  let added = 0;
  let ignored = 0;

  for (const source of sourcesData) {
    try {
      // Upsert: ignore if name exists, else insert
      const res = await prisma.source.upsert({
        where: { name: source.name },
        update: { status: source.status },
        create: {
          name: source.name,
          status: source.status
        }
      });
      added++;
    } catch (error) {
      console.error(`Error processing ${source.name}:`, error);
      ignored++;
    }
  }

  console.log(`Finished seeding sources. Total added/updated: ${added}, Errors: ${ignored}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
